"""add scheduled_messages, news, coin_analyses tables

Revision ID: 78105671fc17
Revises: 30ea80dfc535
Create Date: 2025-07-02 23:07:25.863330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78105671fc17'
down_revision: Union[str, Sequence[str], None] = '30ea80dfc535'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #op.add_column('groups', sa.Column('name', sa.String(), nullable=True))
    #op.add_column('groups', sa.Column('settings', sa.JSON(), nullable=True))
    #op.add_column('groups', sa.Column('welcome_text', sa.Text(), nullable=True))
    #op.add_column('groups', sa.Column('night_mode', sa.Boolean(), nullable=True))
    #op.add_column('groups', sa.Column('created_at', sa.DateTime(), nullable=True))
    #op.add_column('groups', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_index(op.f('ix_groups_id'), table_name='groups')
    op.create_index(op.f('ix_groups_id'), 'groups', ['id'], unique=True)
    op.create_index(op.f('ix_groups_group_id'), 'groups', ['group_id'], unique=True)
    op.drop_column('groups', 'paket_ablauf')
    op.drop_column('groups', 'admin_id')
    op.drop_column('groups', 'paket_status')
    op.drop_column('groups', 'group_name')
    op.add_column('signal_groups', sa.Column('auto_create_groups', sa.Boolean(), nullable=True))
    op.add_column('signal_groups', sa.Column('group_prefix', sa.String(), nullable=True))
    op.add_column('signal_groups', sa.Column('max_members_per_group', sa.Integer(), nullable=True))
    op.add_column('signal_groups', sa.Column('auto_forward_messages', sa.Boolean(), nullable=True))
    op.add_column('signal_groups', sa.Column('forward_delay_seconds', sa.Integer(), nullable=True))
    op.add_column('signal_groups', sa.Column('filter_keywords', sa.Text(), nullable=True))
    op.add_column('signal_groups', sa.Column('exclude_keywords', sa.Text(), nullable=True))
    op.add_column('signal_groups', sa.Column('userbot_session_id', sa.Integer(), nullable=True))
    op.add_column('signal_groups', sa.Column('target_groups', sa.Text(), nullable=True))
    op.add_column('signal_groups', sa.Column('super_group_id', sa.String(), nullable=True))
    op.add_column('signal_groups', sa.Column('themes_config', sa.Text(), nullable=True))
    op.add_column('signal_groups', sa.Column('theme_prices', sa.Text(), nullable=True))
    op.add_column('userbot_sessions', sa.Column('config_data', sa.Text(), nullable=True))
    op.add_column('userbot_sessions', sa.Column('subscription_status', sa.String(), nullable=True))
    op.add_column('userbot_sessions', sa.Column('subscription_start_date', sa.DateTime(), nullable=True))
    op.add_column('userbot_sessions', sa.Column('subscription_end_date', sa.DateTime(), nullable=True))
    op.add_column('userbot_sessions', sa.Column('last_payment_date', sa.DateTime(), nullable=True))
    op.add_column('userbot_sessions', sa.Column('next_payment_date', sa.DateTime(), nullable=True))
    op.add_column('userbot_sessions', sa.Column('payment_reminder_sent', sa.Boolean(), nullable=True))
    op.add_column('userbot_sessions', sa.Column('deletion_warning_sent', sa.Boolean(), nullable=True))
    op.add_column('userbot_sessions', sa.Column('auto_delete_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userbot_sessions', 'auto_delete_date')
    op.drop_column('userbot_sessions', 'deletion_warning_sent')
    op.drop_column('userbot_sessions', 'payment_reminder_sent')
    op.drop_column('userbot_sessions', 'next_payment_date')
    op.drop_column('userbot_sessions', 'last_payment_date')
    op.drop_column('userbot_sessions', 'subscription_end_date')
    op.drop_column('userbot_sessions', 'subscription_start_date')
    op.drop_column('userbot_sessions', 'subscription_status')
    op.drop_column('userbot_sessions', 'config_data')
    op.drop_column('signal_groups', 'theme_prices')
    op.drop_column('signal_groups', 'themes_config')
    op.drop_column('signal_groups', 'super_group_id')
    op.drop_column('signal_groups', 'target_groups')
    op.drop_column('signal_groups', 'userbot_session_id')
    op.drop_column('signal_groups', 'exclude_keywords')
    op.drop_column('signal_groups', 'filter_keywords')
    op.drop_column('signal_groups', 'forward_delay_seconds')
    op.drop_column('signal_groups', 'auto_forward_messages')
    op.drop_column('signal_groups', 'max_members_per_group')
    op.drop_column('signal_groups', 'group_prefix')
    op.drop_column('signal_groups', 'auto_create_groups')
    op.add_column('groups', sa.Column('group_name', sa.TEXT(), nullable=True))
    op.add_column('groups', sa.Column('paket_status', sa.TEXT(), nullable=True))
    op.add_column('groups', sa.Column('admin_id', sa.INTEGER(), nullable=False))
    op.add_column('groups', sa.Column('paket_ablauf', sa.DATETIME(), nullable=True))
    op.drop_index(op.f('ix_groups_group_id'), table_name='groups')
    op.drop_index(op.f('ix_groups_id'), table_name='groups')
    op.create_index(op.f('ix_groups_id'), 'groups', ['id'], unique=True)
    op.drop_column('groups', 'updated_at')
    op.drop_column('groups', 'created_at')
    op.drop_column('groups', 'night_mode')
    op.drop_column('groups', 'welcome_text')
    op.drop_column('groups', 'settings')
    op.drop_column('groups', 'name')
    op.create_table('private_users',
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('last_contact', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('kicks',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('group_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('admin_id', sa.INTEGER(), nullable=False),
    sa.Column('reason', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.group_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('info_settings',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('group_id', sa.INTEGER(), nullable=False),
    sa.Column('info_text', sa.TEXT(), nullable=True),
    sa.Column('info_time', sa.TEXT(), nullable=True),
    sa.Column('info_to_group', sa.BOOLEAN(), server_default=sa.text('1'), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.group_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_users',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('group_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('join_date', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('last_status', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.group_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('group_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('role', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.group_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mutes',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('group_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('admin_id', sa.INTEGER(), nullable=False),
    sa.Column('duration', sa.INTEGER(), nullable=True),
    sa.Column('reason', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.group_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('badwords',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('group_id', sa.INTEGER(), nullable=False),
    sa.Column('word', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.group_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('packages_backup',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.TEXT(), nullable=True),
    sa.Column('price', sa.REAL(), nullable=True),
    sa.Column('duration_days', sa.INTEGER(), nullable=True),
    sa.Column('features', sa.TEXT(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('template_id', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.TEXT(), nullable=True),
    sa.Column('start_date', sa.NUMERIC(), nullable=True),
    sa.Column('end_date', sa.NUMERIC(), nullable=True),
    sa.Column('created_at', sa.NUMERIC(), nullable=True)
    )
    op.create_table('link_exceptions',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('group_id', sa.INTEGER(), nullable=False),
    sa.Column('domain', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.group_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('warnings',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('group_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('admin_id', sa.INTEGER(), nullable=False),
    sa.Column('reason', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.group_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
